language: cpp
os: linux
compiler: gcc
dist: trusty
sudo: required
env: 
    - GCC_VERSION=4
    - GCC_VERSION=5
    - GCC_VERSION=6
    - GCC_VERSION=7

before_install:
    - 'if [ $GCC_VERSION != "4" ]; then
         sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
       fi'
    - sudo apt-get update -q;
    - sudo apt-get install -y cmake cmake-data g++ gcc gfortran build-essential make patch sed
                            libx11-dev libxft-dev libxext-dev libxpm-dev libxmu-dev libglu1-mesa-dev libgl1-mesa-dev
                            ncurses-dev libcurl4-openssl-dev curl bzip2 gzip unzip tar subversion git xutils-dev flex
                            bison lsb-release python-dev libc6-dev-i386 libxml2-dev wget libssl-dev
                            automake autoconf libtool;
    - 'if [ $GCC_VERSION = "5" ]; then
         sudo apt-get install gcc-5 g++-5;
         sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc;
         sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++;
       fi'
    - 'if [ $GCC_VERSION = "6" ]; then
         sudo apt-get install gcc-6 g++-6;
         sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc;
         sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-6 /usr/bin/g++;
       fi'
    - 'if [ $GCC_VERSION = "7" ]; then
         sudo apt-get install gcc-7 g++-7;
         sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc;
         sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++;
       fi'
    - wget https://www.r3broot.gsi.de/system/files/R3BRootBase_1.0.deb;
    - sudo dpkg -i R3BRootBase_1.0.deb;

install:

before_script:
    - $CXX --version
    - cmake --version
    - echo "export LINUX_FLAVOUR=Ubuntu14.04" > Dart.cfg;
    - echo "export EXTRA_FLAGS=\"-DCMAKE_CXX_COMPILER=g++;-DCMAKE_C_COMPILER=gcc\" " >> Dart.cfg;
    - source /opt/R3BRootBase/versions.sh;
    - echo "export FAIRSOFT_VERSION=${FAIRSOFT_VERSION}" >> Dart.cfg;
    - echo "export FAIRROOT_VERSION=${FAIRROOT_VERSION}" >> Dart.cfg;
    - echo "export GIT_BRANCH=${TRAVIS_COMMIT}" >> Dart.cfg;
    - echo "export SIMPATH=/opt/R3BRootBase/build_FairSoft" >> Dart.cfg;
    - echo "export FAIRROOTPATH=/opt/R3BRootBase/install_FairRoot" >> Dart.cfg;
    - echo "export UCESB_DIR=/opt/R3BRootBase/ucesb" >> Dart.cfg;
    - echo "export BUILDDIR=/tmp/r3broot/build_r3broot" >> Dart.cfg;
    - echo "export SOURCEDIR=$PWD" >> Dart.cfg;
    - echo "export SITE=\"Travis CI - ${TRAVIS_PULL_REQUEST} - gcc-${GCC_VERSION}\"" >> Dart.cfg;
    - echo $PWD
    - cat Dart.cfg

script:
    - ./Dart.sh Experimental Dart.cfg

notifications:
    email:
        recipients:
            - Va.Wagner@gsi.de
        on_success: always
        on_failure: always
